# Generated by Django 5.2 on 2025-05-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_packagebooking_email_packagebooking_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
