# Generated by Django 5.2 on 2025-05-16 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_packagebooking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebooking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
